CREATE TABLE IF NOT EXISTS notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TINYTEXT NOT NULL,
  content MEDIUMTEXT NOT NULL,
  created_date DATETIME NOT NULL,
  last_edited_date DATETIME NOT NULL
);
